name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest
    name: CI Checks
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run CI Checks
        uses: ./ # Uses an action in the root directory
        id: verify-rust
